#!/bin/bash
#set -x
########################################################################
#   Batch Job Parameters
########################################################################
#
#### Grid Engine Job Wrapper ####
#
#$ -N 45-64_631gp
#$ -pe mpi2 1
#$ -q wp08
#$ -j y
#$ -m e
#$ -v LD_LIBRARY_PATH,OMP_NUM_THREADS
#
#### Torque/PBS Job Parameters ####
#
#PBS -N 45-64_631gp
#PBS -l nodes=1:ppn=16
#
########################################################################
#   Batch Environment Initialization Commands
########################################################################
#
#### Grid Engine Initialization Commands ####
#
if [ -f $TMPDIR/sge_init.sh ]; then
    source $TMPDIR/sge_init.sh
fi
#
#### Torque/PBS Initialization Commands ####
#
if [ ! -z $PBS_JOBID ]; then
    cd $PBS_O_WORKDIR
fi
#
########################################################################
#   Job Execution Commands
########################################################################
#
export OMP_NUM_THREADS=1
export SCRATCH_DIR=/scratch/$USER/45-64_631gp_$PBS_JOBID

mkdir $SCRATCH_DIR
cp ../struct_h_added/45-64.pdb $SCRATCH_DIR
cp nwc_gbe_631gp_rhf.nw        $SCRATCH_DIR
cd $SCRATCH_DIR
mpiexec -n 16 -x LD_LIBRARY_PATH ~/nwchem/bin/LINUX64/nwchem nwc_gbe_631gp_rhf.nw 
rm -rf $SCRATCH_DIR
