#!/bin/bash
#PBS -A chm136
#PBS -N nwc_gbe_631gp_ccsd_t.074752
#PBS -j oe
#PBS -l walltime=12:00:00,nodes=4672
pwd
ls
export START_DIR=`pwd`/NWX_TA/HUb_1UBQ/nwc_gbe_dgrtl/gto_631gp
export SCRATCH_DIR=$MEMBERWORK/chm136/dgrtl.gto_631gp.74752
export PERMANENT_DIR=$SCRATCH_DIR
mkdir $SCRATCH_DIR
cp $MEMBERWORK/chm136/dgrtl.gto_631gp/* $SCRATCH_DIR
cp NWX_TA/HUb_1UBQ/nwc_gbe_dgrtl/gto_631gp/nwc_gbe_631gp_ccsd_t.nw  $SCRATCH_DIR
#cp NWX_TA/HUb_1UBQ/nwc_gbe_dgrtl/gto_631gp/nwc_gbe_dat.*           $SCRATCH_DIR
#cp NWX_TA/HUb_1UBQ/struct_h_added/dgrtl.pdb                        $SCRATCH_DIR
cp titan/nwchem/bin/LINUX64/nwchem                                  $SCRATCH_DIR
touch $START_DIR/*
touch $SCRATCH_DIR/*
cd $SCRATCH_DIR
export MPICH_USE_DMAPP_COLL=1
export MPICH_GNI_NUM_BUFS=300
export MPICH_GNI_MBOX_PLACEMENT=nic
export MPICH_GNI_LMT_PATH=disabled
export COMEX_MAX_NB_OUTSTANDING=6
export OMP_NUM_THREADS=1
# Titan has only got 2 GB/core
# Set aside  150 MB for the executable and OS
# Set aside   50 MB for the Heap memory section
# Leaves    1848 MB for Stack and Global using the usual key to split this we get
# Stack      616 MB/core equals  80740352 8-byte words
# Global    1232 MB/core equals 161480704 8-byte words
export NWCHEM_MEMORY_HEAP=6553600
#export NWCHEM_MEMORY_STACK=80740352
#export NWCHEM_MEMORY_GLOBAL=161480704
#export NWCHEM_MEMORY_STACK=161480704
#export NWCHEM_MEMORY_GLOBAL=80740352
export NWCHEM_MEMORY_STACK=174937430
export NWCHEM_MEMORY_GLOBAL=67283626
export NWCHEM_BASIS_LIBRARY=/sw/xk6/nwchem/6.6/sles11.3_pgi15.7.0/src/basis/libraries/
export NCORES=$((16*$PBS_NUM_NODES))
aprun -n $NCORES $SCRATCH_DIR/nwchem nwc_gbe_631gp_ccsd_t.nw
ls -ltr
#
# The data sets we generate are too large to bring them back.
# So we leave them here and try to reuse them as much as we
# can before they get purged.
#cp nwc_gbe_dat.db       $START_DIR
#cp nwc_gbe_dat.cfock    $START_DIR
#cp nwc_gbe_dat.movecs   $START_DIR
#cp nwc_gbe_dat.f1int.*  $START_DIR
#cp nwc_gbe_dat.t1amp.*  $START_DIR
#cp nwc_gbe_dat.t2amp.*  $START_DIR
#cp nwc_gbe_dat.v2int.*  $START_DIR
rm -rf $SCRATCH_DIR
